name: Generate Stats

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Classic metrics
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.classic.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, repositories
        plugin_lines: yes
        output_action: commit
        committer_branch: output
        committer_message: "Update Classic Metrics"
    - name: Fortune
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.fortune.svg
        token: NOT_NEEDED
        base: ""
        plugin_fortune: yes
        output_action: commit
        committer_branch: output
        committer_message: "Update Fortune"

    - name: Compact Achievements
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.compact.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_display: compact
        plugin_achievements_threshold: X
        output_action: commit
        committer_branch: output
        committer_message: "Update Compact Achievements"

    - name: Achievements
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_achievements_threshold: X
        output_action: commit
        committer_branch: output
        committer_message: "Update Achievements"

    - name: Topics Icons
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.topics.icons.svg
        token: NOT_NEEDED
        base: ""
        plugin_topics: yes
        plugin_topics_limit: 0
        plugin_topics_mode: icons
        output_action: commit
        committer_branch: output
        committer_message: "Update Topics Icons"

    - name: Most Used Languages (with details)
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.languages.details.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_languages: yes
        plugin_languages_details: bytes-size, percentage
        plugin_languages_limit: 0


